version: '2'

volumes:
  orderer.reliance-network.com:
  peer0.infrastructure.reliance-network.com:
  peer1.infrastructure.reliance-network.com:
  peer0.power.reliance-network.com:
  peer1.power.reliance-network.com:
  peer0.communication.reliance-network.com:
  peer1.communication.reliance-network.com:
  peer0.entertainment.reliance-network.com:
  peer1.entertainment.reliance-network.com:
  peer0.capital.reliance-network.com:
  peer1.capital.reliance-network.com:

networks:
  byfn:

services:


  orderer.reliance-network.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.reliance-network.com
    container_name: orderer.reliance-network.com
    networks:
      - byfn

  peer0.infrastructure.reliance-network.com:
    container_name: peer0.infrastructure.reliance-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.infrastructure.reliance-network.com
    networks:
      - byfn

  peer1.infrastructure.reliance-network.com:
    container_name: peer1.infrastructure.reliance-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.infrastructure.reliance-network.com
    networks:
      - byfn

  peer0.power.reliance-network.com:
    container_name: peer0.power.reliance-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.power.reliance-network.com
    networks:
      - byfn

  peer1.power.reliance-network.com:
    container_name: peer1.power.reliance-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.power.reliance-network.com
    networks:
      - byfn

  peer0.communication.reliance-network.com:
    container_name: peer0.communication.reliance-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.communication.reliance-network.com
    networks:
      - byfn

  peer1.communication.reliance-network.com:
    container_name: peer1.communication.reliance-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.communication.reliance-network.com
    networks:
      - byfn

  peer0.entertainment.reliance-network.com:
    container_name: peer0.entertainment.reliance-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.entertainment.reliance-network.com
    networks:
      - byfn

  peer1.entertainment.reliance-network.com:
    container_name: peer1.entertainment.reliance-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.entertainment.reliance-network.com
    networks:
      - byfn

  peer0.capital.reliance-network.com:
    container_name: peer0.capital.reliance-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.capital.reliance-network.com
    networks:
      - byfn

  peer1.capital.reliance-network.com:
    container_name: peer1.capital.reliance-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.capital.reliance-network.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest #x86_64-1.0.0-rc1
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.infrastructure.reliance-network.com:7051
      - CORE_PEER_LOCALMSPID=infrastructureMSP
      - CORE_PEER_TLS_ENABLED=true 
     
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/infrastructure.reliance-network.com/peers/peer0.infrastructure.reliance-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/infrastructure.reliance-network.com/peers/peer0.infrastructure.reliance-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/infrastructure.reliance-network.com/peers/peer0.infrastructure.reliance-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/infrastructure.reliance-network.com/users/Admin@infrastructure.reliance-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
       
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.reliance-network.com
      - peer0.infrastructure.reliance-network.com
      - peer1.infrastructure.reliance-network.com
      - peer0.power.reliance-network.com
      - peer1.power.reliance-network.com
      - peer0.communication.reliance-network.com
      - peer1.communication.reliance-network.com
      - peer0.entertainment.reliance-network.com
      - peer1.entertainment.reliance-network.com
      - peer0.capital.reliance-network.com
      - peer1.capital.reliance-network.com
    networks:
      - byfn

  # chaincode:
  #   container_name: chaincode
  #   image: hyperledger/fabric-ccenv
  #   tty: true
  #   environment:
  #     - GOPATH=/opt/gopath
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - FABRIC_LOGGING_SPEC=DEBUG
  #     - CORE_PEER_ID=example02
  #     - CORE_PEER_ADDRESS=peer:7051
  #     - CORE_PEER_LOCALMSPID=DEFAULT
  #     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
  #   working_dir: /opt/gopath/src/chaincode
  #   command: /bin/bash -c 'sleep 6000000'
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - ./msp:/etc/hyperledger/msp
  #       - ./../chaincode:/opt/gopath/src/chaincode


